export const TAXONOMY = {
  companies: [
    'OpenAI',
    'Anthropic',
    'Google',
    'Meta',
    'DeepMind',
    'Microsoft',
    'Mistral',
    'xAI',
    'DeepSeek',
    'ByteDance',
    'Alibaba',
    'Tencent',
    'Baidu',
    'Cohere',
    'Stability AI',
    'NVIDIA',
    'Apple',
    'Amazon',
    'Hugging Face',
    'Cursor',
  ] as const,
  models: [
    'GPT-5',
    'GPT-4o',
    'GPT-4',
    'o3',
    'o1',
    'Claude-4',
    'Claude-3.5-Sonnet',
    'Claude-3-Opus',
    'Claude-3-Haiku',
    'Gemini-2',
    'Gemini-1.5-Pro',
    'Gemini-Flash',
    'Llama-4',
    'Llama-3',
    'Mistral-Large',
    'DeepSeek-V3',
    'DeepSeek-R1',
    'Qwen-2.5',
    'Phi-4',
  ] as const,
  categories: [
    'Release',
    'Research',
    'Tutorial',
    'Opinion',
    'Tooling',
    'Benchmark',
    'Incident',
    'Product',
  ] as const,
} as const;

export type Company = (typeof TAXONOMY.companies)[number];
export type Model = (typeof TAXONOMY.models)[number];
export type Category = (typeof TAXONOMY.categories)[number];
